extends SceneTree
var failures := 0
func _initialize() -> void:
	var a := AttemptState.new()
	a.begin(&"monster_truck", [1, 2, 3])
	for p in [1, 2, 3]: a.scene_ready(p, a.id)
	a.observe_accident(1, a.id, &"crushed", Vector3.ZERO)
	a.tick(0.1)
	check(a.phase == &"aftermath", "serious accident immediately guarantees failure")
	var original := a.assessment()
	a.tick(6.0)
	check(a.phase == &"settled", "aftermath finishes before results")
	check(a.assessment() == original, "settlement is immutable")
	var old_id := a.id
	check(not a.choose(1, a.id, 1, &"concede"), "settled outcome cannot be conceded")
	check(a.choose(1, a.id, 1, &"retry"), "first retry choice")
	check(not a.choose(1, a.id, 1, &"waiting_room"), "duplicate choice rejected")
	a.choose(2, a.id, 1, &"waiting_room")
	a.choose(3, a.id, 1, &"retry")
	check(a.phase == &"settled", "mixed choices wait")
	a.choose(2, a.id, 2, &"retry")
	check(a.phase == &"loading" and a.id != old_id, "changed third matching choice retries")
	check(a.choices.is_empty() and a.assessment().is_empty() and a.accidents.is_empty() and a.parking_brake and a.remaining == 360.0, "retry resets attempt")
	check(not a.choose(1, old_id, 100, &"concede"), "previous attempt choice rejected")
	for p in [1, 2, 3]: a.scene_ready(p, a.id)
	a.choose(1, a.id, 1, &"concede")
	a.choose(2, a.id, 1, &"concede")
	a.tick(2.0)
	check(a.phase == &"active" and a.remaining == 358.0, "concession keeps time running")
	a.choose(1, a.id, 2, &"continue")
	a.choose(3, a.id, 1, &"concede")
	check(a.phase == &"active", "withdrawal removes agreement")
	a.choose(1, a.id, 3, &"concede")
	check(a.assessment().reason == &"concession", "three current agreements concede")
	var copy := AttemptState.new()
	copy.restore(a.snapshot())
	check(copy.assessment() == a.assessment() and copy.phase == &"aftermath", "snapshot recovers once-only assessment")
	a.depart()
	check(a.choices.is_empty() and not a.choose(3, a.id, 99, &"retry"), "departure invalidates choices")
	check(a.assessment() == copy.assessment(), "departure preserves settlement")
	for fault in [&"ravine", &"overturn", &"crushed", &"timeout"]:
		a.begin(&"monster_truck", [1, 2, 3])
		for p in [1, 2, 3]: a.scene_ready(p, a.id)
		if fault != &"timeout":
			check(a.observe_accident(1, a.id, fault, Vector3.ZERO), "accept serious observation")
			check(not a.observe_accident(1, a.id, fault, Vector3.ZERO), "duplicate serious observation rejected")
		a.tick(360.0)
		check(a.assessment().reason == fault, "serious observation wins zero tie or timeout settles")
		a.observe_accident(1, a.id, &"rescued", Vector3.ZERO)
		check(a.assessment().reason == fault and a.assessment().outcome == &"failed", "physical recovery cannot revoke failure")
		var immutable := a.assessment()
		immutable["outcome"] = &"passed"
		check(a.assessment().outcome == &"failed", "caller cannot mutate shared outcome")
	var room := RoomState.new()
	for p in [1, 2, 3]:
		room.arrive(p, "Fixture")
		room.pick(p, &"monster_truck")
		room.sit(p, p)
	room.tick(3.0)
	for p in [1, 2, 3]: room.attempt.scene_ready(p, room.attempt.id)
	room.attempt.choose(1, room.attempt.id, 1, &"concede")
	room.attempt.choose(2, room.attempt.id, 1, &"concede")
	room.leave(3)
	check(room.attempt.phase == &"departing" and room.attempt.assessment().is_empty(), "guest departure abandons unfinished concession race")
	check(not room.attempt.choose(3, room.attempt.id, 1, &"concede"), "departed third agreement rejected")
	if failures == 0: print("PASS: failure boundary")
	quit(1 if failures else 0)
func check(ok: bool, description: String) -> void:
	if not ok:
		failures += 1
		printerr("FAIL: ", description)
